services:
  - type: web
    name: sword-shop
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: sword-shop-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: sword-shop-db
    databaseName: sword_shop
    user: sword_shop_user
