services:
  - type: web
    name: meu-app
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: SESSION_SECRET
        value: minha-chave-shop
